import { buildMetadata } from "../../lib/seo";

export const metadata = buildMetadata({
  title: "Disclaimer | Convertixy",
  description:
    "Read the official disclaimer page of Convertixy to understand platform usage, informational content, user responsibilities, and website policies.",
  slug: "/disclaimer",
  keywords: [
    "convertixy disclaimer",
    "website disclaimer",
    "online tools disclaimer",
    "platform policy",
    "tool usage information",
    "legal disclaimer",
    "convertixy policies",
    "website information",
  ],
  focusKeyword: "Convertixy Disclaimer",
});

export default function DisclaimerPage() {
  return (
    <section className="bg-gradient-to-b from-slate-50 to-white py-14 sm:py-20">
      <div className="mx-auto max-w-5xl px-4 sm:px-6 lg:px-8">
        {/* Header */}
        <header className="mb-14 text-center">
          <h1 className="text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl md:text-5xl">
            Disclaimer
          </h1>

          <p className="mx-auto mt-4 max-w-3xl text-base leading-relaxed text-gray-600 sm:text-lg">
            This disclaimer explains the general purpose of Convertixy, how
            users can use the platform, and important information related to
            website content and online tools.
          </p>
        </header>

        {/* Main Content */}
        <div className="space-y-12 rounded-3xl border border-gray-200 bg-white p-6 text-gray-800 shadow-sm sm:p-10 md:p-12">
          {/* Section 1 */}
          <section>
            <h2 className="mb-4 text-2xl font-semibold text-gray-900">
              General Information
            </h2>

            <p className="leading-relaxed">
              Convertixy provides online tools, utilities, and informational
              content for general educational and productivity purposes. While
              we aim to keep all information accurate and updated, users should
              independently verify results when necessary before making
              important decisions.
            </p>
          </section>

          {/* Section 2 */}
          <section>
            <h2 className="mb-4 text-2xl font-semibold text-gray-900">
              Tool Usage
            </h2>

            <p className="leading-relaxed">
              Our tools are designed to help users complete digital tasks more
              efficiently. Results generated by calculators, converters, text
              utilities, or file tools may vary depending on user inputs,
              browser compatibility, and technical factors.
            </p>
          </section>

          {/* Section 3 */}
          <section>
            <h2 className="mb-4 text-2xl font-semibold text-gray-900">
              Content Accuracy
            </h2>

            <p className="leading-relaxed">
              We regularly review and improve platform content to maintain
              quality and usability. However, Convertixy does not guarantee that
              all information will always remain fully complete, current, or
              error-free.
            </p>
          </section>

          {/* Section 4 */}
          <section>
            <h2 className="mb-4 text-2xl font-semibold text-gray-900">
              External Links
            </h2>

            <p className="leading-relaxed">
              Some pages on Convertixy may include links to third-party
              websites or external resources for additional information and user
              convenience. We do not control external websites and are not
              responsible for their content, services, or privacy practices.
            </p>
          </section>

          {/* Section 5 */}
          <section>
            <h2 className="mb-4 text-2xl font-semibold text-gray-900">
              Responsible Use
            </h2>

            <p className="leading-relaxed">
              Users are expected to use Convertixy responsibly and in accordance
              with applicable laws and regulations. Misuse of tools, automated
              abuse, or activities that negatively affect platform performance
              may result in restricted access.
            </p>
          </section>

          {/* Section 6 */}
          <section>
            <h2 className="mb-4 text-2xl font-semibold text-gray-900">
              Platform Updates
            </h2>

            <p className="leading-relaxed">
              Convertixy may update, modify, improve, or remove platform
              features, content, and tools at any time in order to improve user
              experience, security, and performance.
            </p>
          </section>

          {/* Section 7 */}
          <section>
            <h2 className="mb-4 text-2xl font-semibold text-gray-900">
              Contact Information
            </h2>

            <p className="leading-relaxed">
              If you have questions regarding this disclaimer or any part of the
              platform, you can contact us at{" "}
              <a
                href="mailto:contact@convertixy.com"
                className="font-medium text-indigo-600 transition hover:text-indigo-700 hover:underline"
              >
                contact@convertixy.com
              </a>
              .
            </p>
          </section>
        </div>

        {/* Footer Note */}
        <div className="mt-10 text-center">
          <p className="text-sm leading-relaxed text-gray-500">
            By using Convertixy, users acknowledge and agree to the terms
            outlined in this disclaimer page.
          </p>
        </div>
      </div>
    </section>
  );
}