import { buildMetadata } from "../../lib/seo";

export const metadata = buildMetadata({
  title: "Disclaimer",
  description:
    "Disclaimer for Convertixy: important notices regarding information accuracy, liability, and usage of our tools.",
  slug: "/disclaimer",
  keywords: ["disclaimer", "liability", "information", "notice", "accuracy"],
});

export default function DisclaimerPage() {
  return (
    <section className="bg-gray-50 py-12 sm:py-16">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Header */}
        <header className="text-center mb-10">
          <h1 className="text-3xl sm:text-4xl md:text-5xl font-extrabold text-gray-900">
            Disclaimer
          </h1>
          <p className="mt-3 text-gray-600 text-base sm:text-lg max-w-2xl mx-auto leading-relaxed">
            Please read this disclaimer carefully before using Convertixy and its tools. Transparency and clarity are
            important to us, and this page explains the scope of our responsibility.
          </p>
        </header>

        {/* Content */}
        <div className="bg-white shadow-lg rounded-2xl p-6 sm:p-10 space-y-10 leading-relaxed text-gray-800">
          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mb-3">
              General Information
            </h2>
            <p>
              The content and results generated by Convertixy are provided for general informational purposes only.
              While we strive to keep information and tool outputs accurate and up-to-date, we make no guarantees of
              accuracy, completeness, or suitability for any particular purpose. Users should verify results before
              relying on them.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mb-3">
              No Professional Advice
            </h2>
            <p>
              Outputs from Convertixy tools should not be interpreted as professional advice, including but not limited
              to legal, financial, or medical advice. Always consult a qualified professional for guidance specific to
              your situation. Convertixy is intended for general productivity and convenience only.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mb-3">
              Limitation of Liability
            </h2>
            <p>
              To the maximum extent permitted by law, Convertixy, its team, and contributors shall not be held liable
              for any loss, damage, or consequences arising directly or indirectly from the use of this website or its
              tool outputs. Use of our platform is at your own risk, and by continuing, you accept this limitation of
              liability.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mb-3">
              External Links
            </h2>
            <p>
              Our site may contain links to external websites operated by third parties. These links are provided for
              user convenience only. We do not endorse, control, or take responsibility for the accuracy, content, or
              practices of external websites. Visiting such sites is at your own discretion and risk.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mb-3">
              Contact Us
            </h2>
            <p>
              If you have questions about this disclaimer, please reach out to our legal team at{" "}
              <a
                href="mailto:legal@convertixy.com"
                className="text-indigo-600 hover:underline"
              >
                legal@convertixy.com
              </a>
              . We encourage users to get in touch if they require clarification about the information on this page.
            </p>
          </section>
        </div>
      </div>
    </section>
  );
}
